### PR TITLE
Commit generated templates.js to make changes for issue #103 visible w…

### PR DESCRIPTION
**Pull request by trurli**
…ithout running grunt.

Committed generated templates.js did not reflect template changes (stil had the CSS class missing).

### CODE REVIEW

**Comment by brantje** [comment]
If you want push access to the repo, let me know. 
Thanks!

**Comment by trurli** [comment]
Sure. I'd be happy to work on the export and import stuff, if that's ok. If you've got any thoughts on that, please add them to the issue.

**Comment by brantje** [comment]
Added to repo. Feel free to join our telegram group: https://t.me/NextNote

**Comment by trurli** [comment]
Thanks. Already joined the group. I'm Jakob...

**Pull request merged**
